// A grammar of the names for Lalafell of award winning MMORPG Final Fantasy 14 With Free trial
//  according to the official thread here: https://forum.square-enix.com/ffxiv/threads/61151
export const ff14lalafell = {
  vowels: ['a', 'e', 'i', 'o', 'u'],
  consonants: ['k', 'm', 'n', 'f', 'p', 'w', 'j', 't', 'r', 'l', 'z', 'b'],
  dunesfolk_sultinates: ['Sil', 'Ul'],
  dunesfolk_phoneme: '#consonants##vowels#',
  dunesfolk_male_first: '#a##a##b#',
  dunesfolk_male_second: '#c##c##b#',
  dunesfolk_male_structure: '#dunesfolk_male_first.capitalize# #dunesfolk_male_second.capitalize#',
  dunesfolk_regal_male_structure: '#dunesfolk_male_first.capitalize# #dunesfolk_sultinates# #dunesfolk_male_second.capitalize#',
  dunesfolk_regal_male_name: '#[a:#dunesfolk_phoneme#][b:#dunesfolk_phoneme##dunesfolk_phoneme#][c:#dunesfolk_phoneme#]dunesfolk_regal_male_structure#',
  dunesfolk_male_name: '#[a:#dunesfolk_phoneme#][b:#dunesfolk_phoneme##dunesfolk_phoneme#][c:#dunesfolk_phoneme#]dunesfolk_male_structure#',
  dunesfolk_female_first: '#a##a##b#',
  dunesfolk_female_second: '#a##b#',
  dunesfolk_female_structure: '#dunesfolk_female_first.capitalize# #dunesfolk_female_second.capitalize#',
  dunesfolk_regal_female_structure: '#dunesfolk_female_first.capitalize# #dunesfolk_sultinates# #dunesfolk_female_second.capitalize#',
  dunesfolk_regal_female_name: '#[a:#dunesfolk_phoneme#][b:#dunesfolk_phoneme#]dunesfolk_regal_female_structure#',
  dunesfolk_female_name: '#[a:#dunesfolk_phoneme#][b:#dunesfolk_phoneme#]dunesfolk_female_structure#',
  dunesfolk_name: [
    // By adding more of the thing I want, I can adjust the chance I get more "normal people names" and less Sultans.
    '#dunesfolk_male_name#',
    '#dunesfolk_male_name#',
    '#dunesfolk_male_name#',
    '#dunesfolk_male_name#',
    '#dunesfolk_regal_male_name#',
    '#dunesfolk_female_name#',
    '#dunesfolk_female_name#',
    '#dunesfolk_female_name#',
    '#dunesfolk_female_name#',
    '#dunesfolk_regal_female_name#',
  ],
  plainsfolk_male_start_phoneme: [
    '#vowels##consonants#',
    '#consonants##vowels#',
    '#consonants##vowels##consonants##vowels#',
    '#consonants##vowels##consonants#',
  ],
  plainsfolk_male_end_phoneme: [
    '#consonants##vowels#',
    '#consonants##vowels##consonants##vowels#',
    '#consonants##vowels##consonants#',
  ],
  plainsfolk_male_first: '#a##b#',
  plainsfolk_male_second: '#c##b#',
  plainsfolk_male_structure: '#plainsfolk_male_first.capitalize# #plainsfolk_male_second.capitalize#',
  plainsfolk_male_name: '#[a:#plainsfolk_male_start_phoneme#][b:#plainsfolk_male_end_phoneme#][c:#plainsfolk_male_start_phoneme#]plainsfolk_male_structure#',
  plainsfolk_female_a_phoneme: [
    '#vowels#',
    '#consonants##vowels#',
    '#consonants##vowels##consonants#',
  ],
  plainsfolk_female_b_phoneme: ['#consonants##vowels#', '#consonants##vowels##consonants#'],
  plainsfolk_female_first: '#a##b##b#',
  plainsfolk_female_second: '#a##b#',
  plainsfolk_female_structure: '#plainsfolk_female_first.capitalize# #plainsfolk_female_second.capitalize#',
  plainsfolk_female_name: '#[a:#plainsfolk_female_a_phoneme#][b:#plainsfolk_female_b_phoneme#]plainsfolk_female_structure#',
  plainsfolk_name: [
    '#plainsfolk_male_name#',
    '#plainsfolk_female_name#',
  ],
  lalafell_name: [
    'plainsfolk #plainsfolk_name#',
    'dunesfolk #dunesfolk_name#',
  ],
}
